name: ClassForge Deployment

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        pip install pytest pytest-cov gunicorn
    
    - name: Run tests
      run: |
        pytest tests/backend
    
    - name: Create deployment package
      run: |
        mkdir -p deploy/backend deploy/frontend
        cp -r backend/* deploy/backend/
        cp -r frontend/* deploy/frontend/
        cp LICENSE README.md deploy/
        echo "web: cd backend && gunicorn --workers 4 main:create_app()" > deploy/Procfile
    
    - name: Deploy to Staging
      uses: actions/upload-artifact@v2
      with:
        name: classforge-deployment-package
        path: deploy/
